{% set name = "aws-xray-sdk" %}
{% set version = "2.8.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 90c2fcc982a770e86d009a4c3d2b5c3e372da91cb8284d982bae458e2c0bb268

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv "

requirements:
  host:
    - pip
    - python
  run:
    - python
    - jsonpickle
    - enum34  # [py<34]
    - wrapt
    - future
    - botocore >=1.11.3
    # uses pkg_resources
    - setuptools

test:
  imports:
    - aws_xray_sdk
    - aws_xray_sdk.core
    - aws_xray_sdk.core.emitters
    - aws_xray_sdk.core.exceptions
    - aws_xray_sdk.core.models
    - aws_xray_sdk.core.plugins
    - aws_xray_sdk.core.sampling
    - aws_xray_sdk.core.utils

about:
  home: https://github.com/aws/aws-xray-sdk-python
  license: Apache Software
  license_family: APACHE
  license_file: LICENSE
  summary: The AWS X-Ray SDK for Python (the SDK) enables Python developers to record and emit information from within their applications to the AWS X-Ray service.

extra:
  recipe-maintainers:
    - mariusvniekerk
