{% set name = "aws-xray-sdk" %}
{% set version = "2.9.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b0cd972db218d4d8f7b53ad806fc6184626b924c4997ae58fc9f2a8cd1281568

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv "

requirements:
  host:
    - pip
    - python
    - wheel
  run:
    - python
    - enum34  # [py<34]
    - wrapt
    - future
    - botocore >=1.11.3
    # uses pkg_resources
    - setuptools

test:
  imports:
    - aws_xray_sdk
    - aws_xray_sdk.core
    - aws_xray_sdk.core.emitters
    - aws_xray_sdk.core.exceptions
    - aws_xray_sdk.core.models
    - aws_xray_sdk.core.plugins
    - aws_xray_sdk.core.sampling
    - aws_xray_sdk.core.utils
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/aws/aws-xray-sdk-python
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: The AWS X-Ray SDK for Python (the SDK) enables Python developers to record and emit information from within their applications to the AWS X-Ray service.
  dev_url: https://github.com/aws/aws-xray-sdk-python
  doc_url: https://docs.aws.amazon.com/xray/latest/devguide/aws-xray.html

extra:
  recipe-maintainers:
    - mariusvniekerk
