{% set name = "aws-xray-sdk" %}
{% set version = "2.15.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace('-', '_') }}-{{ version }}.tar.gz
    sha256: 794381b96e835314345068ae1dd3b9120bd8b4e21295066c37e8814dbb341365
  - url: https://github.com/aws/{{ name }}-python/archive/refs/tags/{{ version }}.tar.gz
    sha256: db66fbcde1519ca5db2456d73fe86dae569f39a6c03dbc5a94290783d12f2af1
    folder: gh

build:
  number: 2
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vvv
  skip: true  # [py<37]
  script_env:
    - REQUESTS_CA_BUNDLE=$PREFIX/ssl/cacert.pem  # [not win]
    - REQUESTS_CA_BUNDLE=%PREFIX%\Library\ssl\cacert.pem  # [win]

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - wrapt
    - botocore >=1.11.3

# Relative path issue
{% set ignore_tests = " --ignore=gh/tests/test_async_recorder.py" %}
{% set ignore_tests = ignore_tests + " --ignore=gh/tests/test_recorder.py" %}
{% set ignore_tests = ignore_tests + " --ignore=gh/tests/test_serialize_entities.py" %}
{% set ignore_tests = ignore_tests + " --ignore=gh/tests/test_trace_entities.py" %}
{% set ignore_tests = ignore_tests + " --ignore=gh/tests/test_utils.py" %}
# Missing modules to test externals
{% set ignore_tests = ignore_tests + " --ignore=gh/tests/ext" %}
# >           raise Exception('modules %s are currently not supported for patching'
                            # % ', '.join(unsupported_modules))
# E           Exception: modules tests.mock_module are currently not supported for patching
{% set ignore_tests = ignore_tests + " --ignore=gh/tests/test_patcher.py" %}
# E   ModuleNotFoundError: No module named 'pkg_resources'
{% set ignore_tests = ignore_tests + " --ignore=gh/tests/test_local_sampling_benchmark.py" %}
# ModuleNotFoundError: No module named 'pkg_resources'
{% set ignore_tests = ignore_tests + " --ignore=gh/tests/test_patcher.py" %}  # [py>=314]

{% set disabled_tests = " --deselect=gh/tests/test_async_local_storage.py::test_localstorage_isolation" %}  # [py>=314]

test:
  source_files:
    - gh/tests
  imports:
    - aws_xray_sdk
    - aws_xray_sdk.core
    - aws_xray_sdk.core.async_context
    - aws_xray_sdk.core.context
    - aws_xray_sdk.core.daemon_config
    - aws_xray_sdk.core.emitters.udp_emitter
    - aws_xray_sdk.core.exceptions.exceptions
    - aws_xray_sdk.core.lambda_launcher
    - aws_xray_sdk.core.models
    - aws_xray_sdk.core.models.dummy_entities
    - aws_xray_sdk.core.models.facade_segment
    - aws_xray_sdk.core.models.segment
    - aws_xray_sdk.core.models.subsegment
    - aws_xray_sdk.core.models.throwable
    - aws_xray_sdk.core.models.trace_header
    - aws_xray_sdk.core.models.traceid
    - aws_xray_sdk.core.patcher
    - aws_xray_sdk.core.plugins.utils
    - aws_xray_sdk.core.recorder
    - aws_xray_sdk.core.sampling.local.sampler
    - aws_xray_sdk.core.sampling.local.sampling_rule
    - aws_xray_sdk.core.sampling.reservoir
    - aws_xray_sdk.core.sampling.rule_cache
    - aws_xray_sdk.core.sampling.sampler
    - aws_xray_sdk.core.sampling.sampling_rule
    - aws_xray_sdk.core.utils
    - aws_xray_sdk.core.utils.search_pattern
    - aws_xray_sdk.core.utils.sqs_message_helper
    - aws_xray_sdk.version
  requires:
    - pip
    - pytest
    # Starting from version 0.23.0 fixture event_loop is not available
    # E       fixture 'event_loop' not found
    # According to upstream documentation
    # https://github.com/aws/aws-xray-sdk-python/blob/48b6a8f2bb134c84b283666d1c2b4c1e9e6def6f/tox.ini#L61
    - pytest-asyncio ==0.21.2  # [py<314]
    - pytest-asyncio  # [py>=314]
    - pytest-benchmark
    # Tests require a valid CA bundle with the path to certificates.
    # ca-certificates contains needed certificates.
    - ca-certificates
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -vv {{ ignore_tests }} gh/tests  # [py<314]
    - pytest -vv {{ ignore_tests }} {{ disabled_tests }} gh/tests  # [py>=314]

about:
  home: https://github.com/aws/aws-xray-sdk-python
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: The AWS X-Ray SDK for Python (the SDK) enables Python developers to record and emit information from within their applications to the AWS X-Ray service.
  description: 
    The AWS X-Ray SDK for Python (the SDK) enables Python developers to record and emit information from within their applications to the AWS X-Ray service.
  dev_url: https://github.com/aws/aws-xray-sdk-python
  doc_url: https://docs.aws.amazon.com/xray/latest/devguide/aws-xray.html

extra:
  recipe-maintainers:
    - mariusvniekerk
  skip-lints:
    - missing_imports_or_run_test_py